#!/usr/bin/env node
/* ============================================================
   scripts/fetch-symbols.mjs — generate the Material Symbols registry.

   To add an icon for use in the app or in content data:
     1. add its Material Symbol name to MANIFEST below
     2. run `npm run fetch:symbols`
   It downloads the official Rounded (outlined, weight 400) SVG for each
   name and writes js/icons/material-symbols.js — a tiny registry +
   `window.ECONOS_SYM(name, size)` helper. The site stays offline-first:
   the paths are inlined, no font, no network at runtime.

   Browse names at https://fonts.google.com/icons (style: Rounded).
   ============================================================ */
import { writeFileSync } from 'node:fs';

const MANIFEST = [
  // — sidebar nav —
  'home', 'menu_book', 'bar_chart', 'quiz', 'calendar_month', 'chat_bubble', 'settings',
  // — common UI —
  'check_circle', 'cancel', 'info', 'warning', 'error', 'help', 'lightbulb', 'target',
  'bolt', 'schedule', 'flag', 'rocket_launch', 'star', 'bookmark', 'visibility',
  'arrow_forward', 'arrow_back', 'trending_up', 'trending_down', 'trending_flat',
  'swap_horiz', 'north_east', 'south_east',
  // — economics —
  'account_balance', 'payments', 'savings', 'paid', 'percent', 'price_change',
  'currency_pound', 'currency_exchange', 'account_balance_wallet', 'real_estate_agent',
  'public', 'language', 'group', 'groups', 'person', 'school', 'balance', 'gavel',
  'factory', 'agriculture', 'store', 'shopping_cart', 'work', 'engineering', 'science',
  'query_stats', 'monitoring', 'handshake', 'recycling', 'eco',
  'local_shipping', 'inventory_2', 'sentiment_satisfied', 'sentiment_dissatisfied',
];

const base = 'https://cdn.jsdelivr.net/npm/@material-symbols/svg-400/rounded';

const reg = {};
const failed = [];
for (const name of [...new Set(MANIFEST)]) {
  try {
    const res = await fetch(`${base}/${name}.svg`);
    if (!res.ok) { failed.push(`${name}(${res.status})`); continue; }
    const svg = await res.text();
    const inner = svg.match(/<svg[^>]*>([\s\S]*?)<\/svg>/)[1].trim();
    // store just the path d (each symbol is a single <path>)
    const d = inner.match(/<path[^>]*\bd="([^"]+)"/);
    reg[name] = d ? d[1] : inner;
  } catch (e) {
    failed.push(`${name}(${e.message})`);
  }
}

const body = `/* eslint-env browser */
/* ============================================================
   js/icons/material-symbols.js — Material Symbols registry (Rounded,
   outlined, weight 400). GENERATED by scripts/fetch-symbols.mjs — do not
   edit by hand; add a name to that script's MANIFEST and re-run.

   Usage:
     window.ECONOS_SYM('bar_chart', 20)  -> '<svg ...>'  (inherits currentColor)
   In content data, set an icon field to 'sym:<name>', e.g.
     { icon: 'sym:rocket_launch' }
   ============================================================ */
(function () {
  'use strict';
  var P = ${JSON.stringify(reg, null, 0)};
  function sym(name, size) {
    var d = P[name];
    if (!d) return '';
    var s = size || 20;
    return '<svg viewBox="0 -960 960 960" width="' + s + '" height="' + s +
      '" fill="currentColor" aria-hidden="true" focusable="false"><path d="' + d + '"/></svg>';
  }
  if (typeof window !== 'undefined') {
    window.ECONOS_MSYM = P;
    window.ECONOS_SYM = sym;
  }
})();
`;

writeFileSync('js/icons/material-symbols.js', body);
console.log(`material-symbols.js: ${Object.keys(reg).length} symbols written.`);
if (failed.length) console.log('FAILED:', failed.join(', '));
